### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by wenchyron** [DreaminginCodeZH/MaterialColdStart#10]
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
bash: line 1: gcalccmd: command not found
bash: line 1: bc: command not found
xargs: printf: terminated by signal 13
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found

**Comment by zhanghai** [comment]
You need to install bc, inkscape and gcalccmd (from gnome-calculator).
