### ISSUE TITLE
bash: line 1: gcalccmd: command not found ../shsvg/shsvgdpi.sh: line 67: inkscape: command not found

### ISSUE THREAD

**Issue by i91h1r** [DreaminginCodeZH/MaterialColdStart#13]
bash: line 1: gcalccmd: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found

**Comment by hyr0318** [comment]
bash: line 1: gcalccmd: command not found
../shsvg/shsvgdpi.sh: line 67: inkscape: command not found

**Comment by i91h1r** [comment]
Requires bash, bc, gcalccmd (from gnome-calculator) and inkscape.   不知道什么意思额，该怎么操作？

**Comment by zhanghai** [comment]
You need to install `gnome-calculator` and `inkscape` with your package manager.

需要用你的包管理器安装 `gnome-calculator` 和 `inkscape`。

**Comment by i91h1r** [comment]
请问怎么安装额？ 这方面我还不太懂额？可以说下么

**Comment by zhanghai** [comment]
Please Google.

请 Google 你的发行版名 + “安装软件包”。

**Comment by i91h1r** [comment]
gnome-calculator 这个已经安装了。但是 inkscape ， google 了 还是不明白怎么安装。你可以做一张没有tablayout的一张.9的图么，inkscape 实在是不知道怎么安装额。。。。

**Comment by i91h1r** [comment]
大神，帮个忙额，，，，帮我做一个没有tablayout的.9也行额，，，我这边用的windows ，装bc, gcalccmd inkscape 总是出现一推的问题不能运行成功额。。。。谢谢啦

**Comment by zhanghai** [comment]
私聊，我看不到你的邮箱地址，我的邮箱在源码中有。
