### ISSUE TITLE
大神能否出一个中文文档, 这个英文文档说实话觉得有点晦涩

### ISSUE THREAD

**Issue by NikiLee2016** [DreaminginCodeZH/MaterialColdStart#15]

**Comment by NikiLee2016** [comment]
![image](https://user-images.githubusercontent.com/28485853/47210869-af219880-d3c6-11e8-9cb5-3965492ced28.png)
mac 上命令执行之后出现以上信息, 然后生成了一堆空文件夹
![image](https://user-images.githubusercontent.com/28485853/47210946-db3d1980-d3c6-11e8-944b-938e102ee0ee.png)

**Comment by zhanghai** [comment]
脚本里用到了 gnome-calculator 提供的 gcalccmd，可以在 Linux 上试一试，也可以自己修改脚本来调用其他的工具

**Comment by NikiLee2016** [comment]
好的, 一开始对gnome-calculator不熟悉, 现在了解了. 谢谢!
