### ISSUE TITLE
Support only Toolbar without TabLayout

### ISSUE THREAD

**Issue by vanniktech** [DreaminginCodeZH/MaterialColdStart#3]
If you have an application which only uses the Toolbar and no TabLayout the generated nine patch drawable is too big.

Having an option to say if you use both, Toolbar and TabLayout or only Toolbar and hence changing the height would solve that problem.

**Comment by zhanghai** [comment]
As in the usage section of README:

> 1. Modify the .conf files to reflect the layout of your main activity. You can set some of the values to 0 so that the corresponding area will be hidden.

And in this case you can set APPBAR_HEIGHT=56 or 64 in different conf files.

**Comment by zhanghai** [comment]
Added an example to README.

**Comment by vanniktech** [comment]
Okay cool thanks. Will try it out later.

**Comment by vanniktech** [comment]
My colors.conf looks like this:

```
COLOR_PRIMARY_DARK=#388e3c
COLOR_PRIMARY=#4caf50
COLOR_WINDOW_BACKGROUND=#eeeeee
COLOR_SHADOW_START=#000000
COLOR_SHADOW_START_OPACITY=0.215686275
COLOR_SHADOW_END=#000000
COLOR_SHADOW_END_OPACITY=0.011764706
APPBAR_HEIGHT=56
```

However the generated nine patch is still too big. Is there something else I need to configure?

**Comment by zhanghai** [comment]
@vanniktech colors.conf is sourced by other specific configurations; it is only intended to define colors.

You should change `APPBAR_HEIGHT` in `raw{,-sw600dp}{,-v23}`/window_background_statusbar_toolbar_tab.9.shsvg.conf — Also notice that APPBAR height is 64 in sw600dp.

I'm working on some sort of resource overriding trick - by automatically sourcing confs in certain order.
