### ISSUE TITLE
Not working in 4.4.2 devices

### ISSUE THREAD

**Issue by GrenderG** [DreaminginCodeZH/MaterialColdStart#7]
In Samsung Galaxy S2 i9100 with CyanogenMod 4.4.2 and in Nexus One 4.4.2 (AOSP) it's not working, I get this:

![device-2016-01-17-234133](https://cloud.githubusercontent.com/assets/8654362/12380469/11b207ee-bd74-11e5-90d4-c41f5c873f05.png)

**Comment by zhanghai** [comment]
Please attach the generated nine-patches for investigation.

**Comment by GrenderG** [comment]
Thanks for you reply. You can found them here:

https://github.com/GrenderG/TinyList/tree/master/app/src/main/res

Regards, Dani.

**Comment by zhanghai** [comment]
Sorry for the delay, I was much too busy with my finals.

Did this work for some of the devices? A quick glance on some of the nine-patches seems correct. Can this be DPI-specific?

**Comment by GrenderG** [comment]
Yeah it works in some devices, in fact in the devices that doesn't work with 4.4.2, it does if I change to 5.1.1.

**Comment by GrenderG** [comment]
Hello, any news about this issue?

**Comment by zhanghai** [comment]
Hmm... Because I cannot reproduce it with [my own app](https://github.com/DreaminginCodeZH/Douya) which employed this technique, on my 4.4.2 Nexus 5 / Nexus 9 emulator.

The underlying mechanism is just some 9-patches. Maybe you misconfigured some of the parameters in `raw` (`raw-v23` overrides the parameters for 5.0+)?

Can you provide the modified files of this project for generating those 9-patches? Or a minimal testcase reproducing this issue, etc.

**Comment by GrenderG** [comment]
Have you tried with an AOSP based rom?

**Comment by zhanghai** [comment]
Currently I don't have any physical 4.x device at hand, so I can only test on AOSP roms of emulator.

But I don't tend to believe this is a ROM-specific issue - after all it is a 9-patch rendering which has been around for a long time.

Can you reproduce this issue of your app on all 4.x devices? Or is it specific to only some of the 4.x devices?

**Comment by GrenderG** [comment]
Tested in Nexus 5 with 4.4.2 AOSP and it's working perfectly, but in Nexus One and Galaxy S2 (also 4.4.2 AOSP) it's not. Weird :/

**Comment by zhanghai** [comment]
Oop, there's another possibility, hdpi, which is 1.5x and can lead to rounding problems (status bar on 4.x is 25dp which is odd). Will check it later.

**Comment by GrenderG** [comment]
Okay! Keep me informed :)

**Comment by zhanghai** [comment]
@GrenderG 

I've fixed that hdpi rounding issue in my early experiments, so it is not the cause this time.

Take a look at [your hdpi asset](https://github.com/GrenderG/TinyList/blob/master/app/src/main/res/drawable-hdpi/window_background_statusbar_toolbar_tab.9.png), it is 1998px in height, while the correct height should be 136px. Should be something when you are generating the assets.

**Comment by GrenderG** [comment]
I have generated it and I get a 1998px asset again :/ I've only changed primary and primary dark color. (Done in Ubuntu 14.04)

**Comment by zhanghai** [comment]
@GrenderG Please attach your copy of this repo for 9-patch generation and I'll see if I can reproduce.

**Comment by GrenderG** [comment]
Take a look [here](https://mega.nz/#!1BxhCABL!38Sx9BuQiuL3JXi6mXCNQc845AC7EC5VZq4ICJQpIEU) (mega).

**Comment by zhanghai** [comment]
Cannot reproduce - it is 3 x 203 px when generated by me on my Arch Linux distribution.

![window_background_statusbar_toolbar_tab 9](https://cloud.githubusercontent.com/assets/4469895/14352915/53ce2ad4-fd09-11e5-8cf5-5d2385c638eb.png)

You can try to comment out [this line](https://github.com/DreaminginCodeZH/AndroidSVGScripts/blob/7dc6a6a1acf4f5329a42d5ed629c3a95366f761e/shsvgdpi.sh#L69) and check the generated size in svg file and to if it's an error in the `calc` and `dp` functions.

**Comment by GrenderG** [comment]
[drawable-hdpi.zip](https://github.com/DreaminginCodeZH/MaterialColdStart/files/208552/drawable-hdpi.zip)

Same, 1998 px in the svg file.

**Comment by zhanghai** [comment]
@GrenderG Then it must be something related to Ubuntu distributed binaries - and some command that is possibly related to the rounding part. See `shsvg.sh`.

If you know some bash scripting, you can try to identify the issue yourself - or if you can't, I'll take a look tomorrow or so.

**Comment by GrenderG** [comment]
Unfortunately  I don't know much about bash scripting.

EDIT: Tried using the last version of Inkscape, still 1998px.

**Comment by GrenderG** [comment]
UPDATE: Tried with Ubuntu 16.04, and still the same.
